steps:
  # Decrypt
  - name: "gcr.io/cloud-builders/gcloud"
    args:
    - kms
    - decrypt
    -  --ciphertext-file=.env.enc
    - --plaintext-file=.env
    - --location=global
    - --keyring=react-firebase-authentication 
    - --key=cloudbuild-env
steps:
  # Instal
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  # Instal firebase globaly
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "-g", "firebase-tools"]

  # # Run
  # - name: 'gcr.io/cloud-builders/npm'
  #   args: ['run']

  # Build
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  # # Build
  # - name: "gcr.io/authentication-app-2daff/firebase"
  #   args: ["deploy"]

  # Deploy
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "deploy"]
