steps:
  # Decrypt
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=react-firebase-authentication
      - --key=cloudbuild-env

  # Instal
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]

  # Build
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "build"]

  # Deploy
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "deploy"]
# Instal firebase globaly
# - name: "gcr.io/cloud-builders/npm"
#   args: ["install", "-g", "firebase-tools"]
# # Build
# - name: "gcr.io/authentication-app-2daff/firebase"
#   args: ["deploy"]
